# Generated by Django 4.2.6 on 2024-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot', '0002_question_user_remove_userform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userform',
            name='registration_number',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
