# Generated by Django 4.2.6 on 2024-08-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot', '0003_userform_name_userform_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicebot.userform'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
