# Generated by Django 4.2.6 on 2024-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot', '0005_remove_answer_answer_text_remove_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_results/'),
        ),
    ]
