# Generated by Django 4.2.6 on 2024-09-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot', '0007_question_options_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
